// This file is auto-generated by @hey-api/openapi-ts

export type Company = {
    /**
     * Company name
     */
    name: string;
    /**
     * Source link (URL)
     */
    source: string;
    /**
     * Published status
     */
    published: boolean;
    /**
     * Date added
     */
    createdAt: string;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    /**
     * Application is running
     */
    200: {
        message?: string;
        timestamp?: string;
        version?: string;
    };
};

export type AppControllerGetHelloResponse = AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type AppControllerGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type AppControllerGetHealthResponses = {
    /**
     * Service is healthy
     */
    200: {
        status?: string;
        uptime?: number;
    };
};

export type AppControllerGetHealthResponse = AppControllerGetHealthResponses[keyof AppControllerGetHealthResponses];

export type AuthControllerSignUpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type AuthControllerSignUpResponses = {
    201: unknown;
};

export type AuthControllerSignInData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/signin';
};

export type AuthControllerSignInResponses = {
    201: unknown;
};

export type AuthControllerChangePasswordData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type AuthControllerChangePasswordResponses = {
    201: unknown;
};

export type CompanyControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/companies';
};

export type CompanyControllerFindAllResponses = {
    /**
     * List all companies
     */
    200: Array<Company>;
};

export type CompanyControllerFindAllResponse = CompanyControllerFindAllResponses[keyof CompanyControllerFindAllResponses];

export type CompanyControllerCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/companies';
};

export type CompanyControllerCreateResponses = {
    /**
     * Created company
     */
    200: Company;
};

export type CompanyControllerCreateResponse = CompanyControllerCreateResponses[keyof CompanyControllerCreateResponses];

export type CompanyControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/companies/{id}';
};

export type CompanyControllerRemoveErrors = {
    /**
     * Company not found
     */
    404: unknown;
};

export type CompanyControllerRemoveResponses = {
    /**
     * Delete company by id
     */
    200: {
        [key: string]: unknown;
    };
};

export type CompanyControllerRemoveResponse = CompanyControllerRemoveResponses[keyof CompanyControllerRemoveResponses];

export type CompanyControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/companies/{id}';
};

export type CompanyControllerFindOneErrors = {
    /**
     * Company not found
     */
    404: unknown;
};

export type CompanyControllerFindOneResponses = {
    /**
     * Get company by id
     */
    200: Company;
};

export type CompanyControllerFindOneResponse = CompanyControllerFindOneResponses[keyof CompanyControllerFindOneResponses];

export type CompanyControllerUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/companies/{id}';
};

export type CompanyControllerUpdateErrors = {
    /**
     * Company not found
     */
    404: unknown;
};

export type CompanyControllerUpdateResponses = {
    /**
     * Update company by id
     */
    200: Company;
};

export type CompanyControllerUpdateResponse = CompanyControllerUpdateResponses[keyof CompanyControllerUpdateResponses];

export type FundControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/funds';
};

export type FundControllerFindAllResponses = {
    200: unknown;
};

export type FundControllerCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/funds';
};

export type FundControllerCreateResponses = {
    201: unknown;
};

export type FundControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/funds/{id}';
};

export type FundControllerRemoveResponses = {
    200: unknown;
};

export type FundControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/funds/{id}';
};

export type FundControllerFindOneResponses = {
    200: unknown;
};

export type FundControllerUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/funds/{id}';
};

export type FundControllerUpdateResponses = {
    200: unknown;
};

export type FundControllerGetCompaniesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/funds/{id}/companies';
};

export type FundControllerGetCompaniesResponses = {
    /**
     * List all companies for this fund
     */
    200: Array<Company>;
};

export type FundControllerGetCompaniesResponse = FundControllerGetCompaniesResponses[keyof FundControllerGetCompaniesResponses];

export type PersonalityControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/personalities';
};

export type PersonalityControllerFindAllResponses = {
    200: unknown;
};

export type PersonalityControllerCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/personalities';
};

export type PersonalityControllerCreateResponses = {
    201: unknown;
};

export type PersonalityControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/personalities/{id}';
};

export type PersonalityControllerRemoveResponses = {
    200: unknown;
};

export type PersonalityControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/personalities/{id}';
};

export type PersonalityControllerFindOneResponses = {
    200: unknown;
};

export type PersonalityControllerUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/personalities/{id}';
};

export type PersonalityControllerUpdateResponses = {
    200: unknown;
};

export type PersonalityControllerGetCompaniesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/personalities/{id}/companies';
};

export type PersonalityControllerGetCompaniesResponses = {
    /**
     * List all companies for this personality
     */
    200: Array<Company>;
};

export type PersonalityControllerGetCompaniesResponse = PersonalityControllerGetCompaniesResponses[keyof PersonalityControllerGetCompaniesResponses];

export type SectorControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sectors';
};

export type SectorControllerFindAllResponses = {
    200: unknown;
};

export type SectorControllerCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sectors';
};

export type SectorControllerCreateResponses = {
    201: unknown;
};

export type SectorControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sectors/{id}';
};

export type SectorControllerRemoveResponses = {
    200: unknown;
};

export type SectorControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sectors/{id}';
};

export type SectorControllerFindOneResponses = {
    200: unknown;
};

export type SectorControllerUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sectors/{id}';
};

export type SectorControllerUpdateResponses = {
    200: unknown;
};

export type SectorControllerGetCompaniesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sectors/{id}/companies';
};

export type SectorControllerGetCompaniesResponses = {
    /**
     * List all companies for this sector
     */
    200: Array<Company>;
};

export type SectorControllerGetCompaniesResponse = SectorControllerGetCompaniesResponses[keyof SectorControllerGetCompaniesResponses];

export type ClientOptions = {
    baseUrl: string;
};